"""Added filename to pitch model

Revision ID: 40d933a6b6fc
Revises: d007c96caf2f
Create Date: 2022-03-06 13:44:41.024738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d933a6b6fc'
down_revision = 'd007c96caf2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('filename', sa.String(length=300), nullable=False))
    op.drop_column('pitch', 'content')
    op.drop_column('pitch', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('pitch', sa.Column('content', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.drop_column('pitch', 'filename')
    # ### end Alembic commands ###
